### ISSUE TITLE
Tried to fix it myself but its not working.

### ISSUE THREAD

**Issue by MilkoIvanov** [Exxarion/PMLove#1]
Some directions,maybe?Please

**Comment by Exxarion** [comment]
This project is inactive. Use ServerLoveMCPE on the pocketmine forums if you need a romance plugin.

**Comment by Exxarion** [comment]
I may as well start working on this, when I get the time, of course.

**Comment by MilkoIvanov** [comment]
The idea is great...Anyway thanks for the time

**Comment by thedeibo** [comment]
I suppose this is a bad time for me to ask if i could merge the plugins? (your code and my code running as one)

**Comment by Exxarion** [comment]
I have a plan for this. PM me on the pocketmine forums and we can discuss it.

**Comment by thedeibo** [comment]
Okies
