### ISSUE TITLE
Namespace

### ISSUE THREAD

**Issue by PEMapModder** [Exxarion/PMLove#2]
It is extremely poor practice to name your plugin's namespace `Love`. If someone in the future has a plugin that makes NPC villagers love each other, and he does the same poor practice and name the namespace with a generic name like `Love`, the plugins may conflict.
You should, at least, have the namespace same as your plugin name, by which people can more obviously realize that this namespace may be used and would not use it (unless their plugin name is `PMLove` as well, which is less likely if this plugin is one day widely used). Even better, put your name in the namespace.

**Comment by Exxarion** [comment]
Aight.
